### ISSUE TITLE
Killing towers that belong to teams Custom1 and Custom2 crash the game

### ISSUE THREAD

**Issue by NateR124** [Dota-2-5v5v5v5/GameFolder#1]
Title explains it. I've been able to get a "dota_npc_building" to not crash the game on death (towers are "dota_npc_tower" by default), although solving the problem this way would mean you'd have to rewrite many aspects of the tower (global announcement, bounty distribution, invulernability handling, glyph refund for tier 1, etc.)

**Comment by 14ingrau** [comment]
Thank you, one of the devs actually found that workaround too. Thank you though! ^-^
